sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
os:
  - linux
  - osx
env:
  global:
    - RUST_BACKTRACE=1
script:
  - cargo test
cache:
  cargo: true
  directories:
    - $HOME/.cargo